version: '3.8'

services:

  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: regie
      POSTGRES_PASSWORD: secret
      TZ: UTC
    volumes:
      - regie-pg-local:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  regie-pg-local: